services:
  traefik:
    image: traefik:v2.10.4
    ports:
      # Exposes port 80 for incomming web requests
      - 80:80
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - 8080:8080
      - 9092:9092
      - 27017:27017
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/traefik/conf/traefik.yml:/etc/traefik/traefik.yml

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.mongo.loadbalancer.server.port=27017"
      - "traefik.tcp.routers.mongo.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mongo.entrypoints=mongo"
    volumes:
      - mongo:/data/db
      - ./app/mongo/conf:/etc/mongo

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL
      - ME_CONFIG_MONGODB_ENABLE_ADMIN
      - ME_CONFIG_MONGODB_AUTH_USERNAME
      - ME_CONFIG_MONGODB_AUTH_PASSWORD
      - ME_CONFIG_BASICAUTH
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD
      - ME_CONFIG_REQUEST_SIZE
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-express.rule=Host(`$MONGO_EXPRESS_DNS`)"
      - "traefik.http.routers.mongo-express.entrypoints=web"
      - "traefik.http.routers.mongo-express.service=mongo-express"
      - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"

  kafka:
    image: bitnami/kafka:3.5.1
    environment:
      - KAFKA_CFG_NODE_ID
      - KAFKA_CFG_PROCESS_ROLES
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
      - KAFKA_CFG_LISTENERS
      - KAFKA_CFG_ADVERTISED_LISTENERS
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.kafka.loadbalancer.server.port=9092"
      - "traefik.tcp.routers.kafka.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.kafka.entrypoints=kafka"
    volumes:
      - "kafka_data:/bitnami"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CLUSTERS_0_NAME
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      - SERVER_SERVLET_CONTEXT_PATH
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kafka-ui.rule=Host(`$KAFKA_UI_DNS`)"
      - "traefik.http.routers.kafka-ui.entrypoints=web"
      - "traefik.http.routers.kafka-ui.service=kafka-ui"
      - "traefik.http.services.kafka-ui.loadbalancer.server.port=8080"

  connect:
    image: debezium/connect
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - ENABLE_DEBEZIUM_SCRIPTING=true
     - CONNECT_REST_EXTENSION_CLASSES=io.debezium.kcrestextension.DebeziumConnectRestExtension

  debezium-ui:
    image: debezium/debezium-ui
    environment:
     - KAFKA_CONNECT_URIS=http://connect:8083
     - DEPLOYMENT_MODE=default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.debezium-ui.rule=Host(`$DEBEZIUM_UI_DNS`)"
      - "traefik.http.routers.debezium-ui.entrypoints=web"
      - "traefik.http.routers.debezium-ui.service=debezium-ui"
      - "traefik.http.services.debezium-ui.loadbalancer.server.port=8080"

volumes: 
  mongo:
  kafka_data: