services:
  traefik:
    image: traefik:v2.10.4
    ports:
      # Exposes port 80 for incomming web requests
      - 80:80
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - 8080:8080
      - 27017:27017
      - 27027:27027
      - 27037:27037
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml

  mongodb-primary:
    container_name: mongodb-primary
    hostname: mongodb-primary
    image: docker.io/bitnami/mongodb:7.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=prisma
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.mongodb-primary.loadbalancer.server.port=27017"
      - "traefik.tcp.routers.mongodb-primary.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mongodb-primary.entrypoints=mongodb-primary"

  mongodb-secondary:
    container_name: mongodb-secondary
    hostname: mongodb-secondary
    image: docker.io/bitnami/mongodb:7.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=prisma
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.mongodb-secondary.loadbalancer.server.port=27017"
      - "traefik.tcp.routers.mongodb-secondary.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mongodb-secondary.entrypoints=mongodb-secondary"

  mongodb-arbiter:
    container_name: mongodb-arbiter
    hostname: mongodb-arbiter
    image: docker.io/bitnami/mongodb:7.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=prisma
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.mongodb-arbiter.loadbalancer.server.port=27017"
      - "traefik.tcp.routers.mongodb-arbiter.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mongodb-arbiter.entrypoints=mongodb-arbiter"
      