################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
    swarmMode: false
    watch: true
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: :80
  mongo1:
    address: :30001
  mongo2:
    address: :30002
  mongo3:
    address: :30003